# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authc', '0002_auto_20170721_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('text', models.TextField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('text', models.TextField()),
                ('title', models.CharField(max_length=25)),
                ('summary', models.TextField(max_length=300)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Weblog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('image', models.TextField(blank=True, max_length=10000, null=True)),
                ('description', models.TextField(blank=True, max_length=25000000, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authc.User')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='weblog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.Weblog'),
        ),
        migrations.AddField(
            model_name='comment',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authc.User'),
        ),
    ]
