# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='postId',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='comment',
            name='pid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='weblog.Post'),
        ),
    ]
