# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0002_auto_20170721_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.TimeField(default=None),
        ),
    ]
