# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0005_auto_20170721_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblog',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
