# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bid',
            field=models.IntegerField(null=True),
        ),
    ]
