# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authc', '0002_auto_20170721_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
